default: &default
  host: localhost
  adapter: postgresql
  encoding: UTF8
  username: sinatra_admin
  timeout: 5000
  reaping_frequency: 30
  pool: 5

development:
  <<: *default
  database: sinatra_seq_dev
  password: sinatra_admin

test:
  <<: *default
  database: sinatra_seq_test
  password: sinatra_admin

production:
  <<: *default
  database: sinatra_seq_prod
  password: sinatra_admin