source 'https://rubygems.org'

gem 'rackup'
gem 'rack'
gem 'rake'

gem 'sinatra'
gem 'sinatra-contrib'

# gem 'activerecord'
# gem 'sinatra-activerecord'
gem 'json'
gem 'pg'

gem 'sequel'
gem 'sequel-seed'

gem 'dotenv'